
apiVersion: v1
kind: Service
metadata:
  name: modresorts10war
  labels:
    app: modresorts10war
spec:
  ports:
    - port: 9080
  selector:
    app: modresorts10war
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: modresorts10war
  name: modresorts10war
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: modresorts10war
    spec:
      containers:
      - image: mycluster.icp:8500/default/modresorts10war:latest
        name: modresorts10war
        ports:
        - containerPort: 9080
          protocol: TCP
